# -*- mode:shell-script -*-

# This file is supposed to be sourced from ~/.bashrc. It contains
# customizations that are applicable for interactive shells.

export EDITOR=emacsclient

shopt -s globstar # Enable globbing of **

for script in ${HOME}/.local/software/**/bash-completions/*; do
    if [ -f "${script}" ]; then
        source "${script}"
    fi
done

for version in 9 8 7; do
    clang_bash_completions=/usr/lib/llvm-${version}/share/clang/bash-autocomplete.sh
    if [ -r "${clang_bash_completions}" ]; then
        source "${clang_bash_completions}"
        break
    fi
done

alias l="git log --stat"
alias s="git status"
alias d="git diff"
alias a="git add"
alias c="git commit"

function find_source_root()
{
    dirname "$(readlink -f "${BASH_SOURCE[0]}")"
}

source "$(find_source_root)"/prompt/loudprompt.sh
